# Generated by Django 4.1.5 on 2023-02-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_age", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="нижняя граница")),
                ("to_age", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="верхняя граница")),
            ],
            options={
                "verbose_name": "возрастное ограничение",
                "verbose_name_plural": "возрастные ограничения",
                "ordering": ("from_age", "to_age"),
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="название")),
            ],
            options={
                "verbose_name": "город",
                "verbose_name_plural": "города",
                "ordering": ("region__country__name", "region__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="название")),
            ],
            options={
                "verbose_name": "страна",
                "verbose_name_plural": "страны",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="название")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="bot.country",
                        verbose_name="страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "регион",
                "verbose_name_plural": "регионы",
                "ordering": ("country__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256, verbose_name="название")),
                (
                    "age_limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bot.agelimit",
                        verbose_name="возрастные ограничения",
                    ),
                ),
                (
                    "cities",
                    models.ManyToManyField(blank=True, related_name="funds", to="bot.city", verbose_name="города"),
                ),
                (
                    "countries",
                    models.ManyToManyField(blank=True, related_name="funds", to="bot.country", verbose_name="страны"),
                ),
                (
                    "regions",
                    models.ManyToManyField(blank=True, related_name="funds", to="bot.region", verbose_name="регионы"),
                ),
            ],
            options={
                "verbose_name": "фонд",
                "verbose_name_plural": "фонды",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="bot.region",
                verbose_name="регион",
            ),
        ),
        migrations.AddConstraint(
            model_name="agelimit",
            constraint=models.CheckConstraint(
                check=models.Q(("from_age", None), ("to_age", None), _negated=True),
                name="Нужно указать хотя бы одно значение",
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(fields=("name", "region"), name="Unique city in region"),
        ),
    ]
