# Generated by Django 4.1.5 on 2023-02-05 13:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="название")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name": "зона охвата",
                "verbose_name_plural": "зоны охвата",
            },
        ),
        migrations.AlterModelOptions(
            name="fund",
            options={"ordering": ("name",), "verbose_name": "фонд", "verbose_name_plural": "фонды"},
        ),
        migrations.RenameModel(
            old_name="limitation",
            new_name="AgeLimit",
        ),
        migrations.AlterModelOptions(
            name="agelimit",
            options={
                "ordering": ("from_age", "to_age"),
                "verbose_name": "возрастное ограничение",
                "verbose_name_plural": "возрастные ограничения",
            },
        ),
        migrations.RemoveField(
            model_name="fund",
            name="city",
        ),
        migrations.RenameField(
            model_name="fund",
            old_name="limitation",
            new_name="age_limit",
        ),
        migrations.AlterField(
            model_name="fund",
            name="age_limit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="bot.agelimit",
                verbose_name="возрастные ограничения",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fund",
            name="description",
            field=models.TextField(default="Описание", verbose_name="описание"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fund",
            name="name",
            field=models.CharField(max_length=256, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="agelimit",
            name="from_age",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="нижняя граница"),
        ),
        migrations.AlterField(
            model_name="agelimit",
            name="to_age",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="верхняя граница"),
        ),
        migrations.AddConstraint(
            model_name="agelimit",
            constraint=models.UniqueConstraint(fields=("from_age", "to_age"), name="Unique age limit"),
        ),
        migrations.AddConstraint(
            model_name="agelimit",
            constraint=models.CheckConstraint(
                check=models.Q(("from_age", None), ("to_age", None), _negated=True),
                name="Нужно указать хотя бы одно значение",
            ),
        ),
        migrations.AddField(
            model_name="coveragearea",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="bot.coveragearea",
                verbose_name="родительская зона охвата",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="coverage_area",
            field=mptt.fields.TreeManyToManyField(
                related_name="funds", to="bot.coveragearea", verbose_name="зоны охвата"
            ),
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
