# Generated by Django 4.1.5 on 2023-02-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Limitation", new_name="AgeLimit"
        ),
        migrations.AlterModelOptions(
            name="agelimit",
            options={
                "ordering": ("from_age", "to_age"),
                "verbose_name": "возрастное ограничение",
                "verbose_name_plural": "возрастные ограничения",
            },
        ),
        migrations.AlterField(
            model_name="agelimit",
            name="from_age",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="нижняя граница"),
        ),
        migrations.AlterField(
            model_name="agelimit",
            name="to_age",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="верхняя граница"),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="название")),
            ],
            options={
                "verbose_name": "страна",
                "verbose_name_plural": "страны",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="название")),
            ],
            options={
                "verbose_name": "регион",
                "verbose_name_plural": "регионы",
                "ordering": ("country__name", "name"),
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ("region__country__name", "region__name", "name"),
                "verbose_name": "город",
                "verbose_name_plural": "города",
            },
        ),
        migrations.AlterModelOptions(
            name="fund",
            options={"ordering": ("name",), "verbose_name": "фонд", "verbose_name_plural": "фонды"},
        ),
        migrations.RemoveField(
            model_name="fund",
            name="city",
        ),
        migrations.AddField(
            model_name="fund",
            name="cities",
            field=models.ManyToManyField(blank=True, related_name="funds", to="bot.city", verbose_name="города"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="fund",
            name="name",
            field=models.CharField(max_length=256, verbose_name="название"),
        ),
        migrations.AddField(
            model_name="region",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="bot.country",
                verbose_name="страна",
            ),
        ),
        migrations.AddConstraint(
            model_name="agelimit",
            constraint=models.CheckConstraint(
                check=models.Q(("from_age", None), ("to_age", None), _negated=True),
                name="Нужно указать хотя бы одно значение",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="bot.region",
                verbose_name="регион",
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(fields=("name", "region"), name="Unique city in region"),
        ),
        migrations.RenameField(
            model_name="fund",
            old_name="limitation",
            new_name="age_limit",
        ),
        migrations.AlterField(
            model_name="fund",
            name="age_limit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bot.agelimit",
                verbose_name="возрастные ограничения",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="countries",
            field=models.ManyToManyField(blank=True, related_name="funds", to="bot.country", verbose_name="страны"),
        ),
        migrations.AddField(
            model_name="fund",
            name="regions",
            field=models.ManyToManyField(blank=True, related_name="funds", to="bot.region", verbose_name="регионы"),
        ),
    ]
