# Generated by Django 4.1.5 on 2023-02-04 06:45

from django.db import migrations


def add_default_values_to_cities(apps, schema_editor):
    cities = apps.get_model("bot", "City").objects.all()
    if not cities:
        return
    Country = apps.get_model("bot", "Country")
    default_country = Country.objects.create(name="Без страны")
    Region = apps.get_model("bot", "Region")
    default_region = Region.objects.create(
        name="Без региона", country=default_country
    )
    for city in cities:
        city.region = default_region
        city.save()


def add_default_values_to_funds(apps, schema_editor):
    funds = apps.get_model("bot", "Fund").objects.all()
    if not funds:
        return
    default_age_limit = apps.get_model("bot", "AgeLimit").objects.create(
        from_age=18, to_age=None
    )
    for fund in funds:
        if fund.age_limit is None:
            fund.age_limit = default_age_limit
            fund.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_auto_20230204_1645"),
    ]

    operations = [
        migrations.RunPython(add_default_values_to_cities),
        migrations.RunPython(add_default_values_to_funds),
    ]
