# Generated by Django 4.1.5 on 2023-02-04 06:45

from django.db import migrations


def add_default_values(apps, schema_editor):
    Country = apps.get_model("bot", "Country")
    default_country = Country.objects.create(name="Без страны")
    Region = apps.get_model("bot", "Region")
    default_region = Region.objects.create(
        name="Без региона", country=default_country
    )
    City = apps.get_model("bot", "City")
    for city in City.objects.all():
        city.region = default_region
        city.save()
    AgeLimit = apps.get_model("bot", "AgeLimit")
    default_age_limit = AgeLimit.objects.get_or_create(
        from_age=18, to_age=None
    )
    Fund = apps.get_model("bot", "Fund")
    for fund in Fund.objects.all():
        if fund.age_limit is None:
            fund.age_limit = default_age_limit
            fund.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_auto_20230204_1645"),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
