# Generated by Django 4.1.5 on 2023-02-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_auto_20230204_1645"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="bot.region",
                verbose_name="регион",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fund",
            name="age_limit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="bot.agelimit",
                verbose_name="возрастные ограничения",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="region",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="bot.country",
                verbose_name="страна",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="agelimit",
            constraint=models.UniqueConstraint(fields=("from_age", "to_age"), name="Unique age limit"),
        ),
    ]
